default: &default
  adapter: postgresql
  url: "postgres://carnest:CSZGaXi7w1FxtumFuklqe3DgZoQ3OMQL@dpg-cka08mmv3ddc739i8l70-a.oregon-postgres.render.com/carnest"

development:
  <<: *default

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
