default: &default
  adapter: postgresql
  url: "postgres://carnest:2xeJKUzsUsyTlFfOtcbTATbUaabvfTtx@dpg-cke1fbsgonuc7391f8kg-a.oregon-postgres.render.com/carnest_4n4v"

development:
  <<: *default

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
